# Generated by Django 6.0.4 on 2026-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=208)),
                ('userphone', models.CharField(max_length=12)),
                ('userpassword', models.CharField(max_length=200)),
            ],
        ),
    ]
